DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS lfg_posts;
DROP TABLE IF EXISTS custom_cards;
DROP TABLE IF EXISTS plugins;
DROP TABLE IF EXISTS room_actions;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;
